[package]
name = "codex-usage-desktop"
version = "0.1.0"
description = "Codex Usage Desktop"
authors = ["vincent"]
edition = "2021"

[lib]
name = "codex_usage_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

